### ISSUE TITLE
Separate FE from BE

### ISSUE THREAD

**Issue by engineereng** [ubclaunchpad/PromoPal-backend#112] opened 2021-01-27 17:57 UTC
It was mentioned in this past meeting that the Front End of the repo should be split from the Backend. I assume this means that we will need another repo, although it is not clear to me who would do this and how.

This issue is of high priority, as we cannot make further commits before this is done.

**Comment by ericrkuo** [comment] 2021-01-29 02:53
@engineereng I think this is a duplicate of https://github.com/ubclaunchpad/foodies/issues/91. 

I agree this is high priority, @andrewzulaybar since a lot of the PRs in the current repo are related to FE and we have none in BE, we can move the BE to its own repo and keep the FE here? 

But if we want to keep the BE here, I think it'd be okay to just move the FE files to another repo, and then copy and paste the PR changes to the FE repo and make new PRs.

Doesn't matter much to me, I think the only con with moving BE to its own repo is we lose the commit history of the BE since there is quite a lot more of it compared to FE. Commit history could be useful for git blame, but either works!

**Comment by yunishimura0716** [comment] 2021-01-29 07:38
@ericrkuo I agree with his idea, I mean we had better move FE files to another repo due to BE's commits. One thing I'm considering now is how to progress the function which is needed to implement on both FE and BE such as User Auth.

**Comment by ericrkuo** [comment] 2021-01-29 16:35
> @ericrkuo I agree with his idea, I mean we had better move FE files to another repo due to BE's commits. One thing I'm considering now is how to progress the function which is needed to implement on both FE and BE such as User Auth.

Oh ya if the FE is in another repo, then you'll need to work off of two branches, one in BE repo and one in FE repo for user auth. And then you'll need to create 2 PRs and once they're both approved, you'll merge both in at the same time. Not sure if that's what you meant by your question, but lmk if there's more I can clarify!

**Comment by andrewzulaybar** [comment] 2021-01-30 05:31
Working on this right now with @ericrkuo! The course of action we're taking is that we'll move the front-end to a separate repo and this repo will hold the back-end.

**Closed** 2021-01-31 19:38 UTC
Labels: back-end, front-end
